### ISSUE TITLE
Add blindInputs function to blinder

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#105]
Taking into account all the considerations of #97 we should add to the `*blinder` type one unexported method `blindInputs` that takes care of blinding all the issuances contained in the inputs of the transaction (1 input can have only 1 issuance, remember).

The fields that must be blinded in a input issuance are the asset and the token amount.
It's worth to remember that an issuance can have a not defined token amount, thus, in this case, only the asset amount has to be blinded, while a reissuance has only an asset amount that needs to be blinded.

For blinding an asset amount it's necessary to do the following steps:
1. generate a random value blinding factor
1. generate a random asset blinding factor
1. generate the asset commitment (needed only for the following step)
1. generate the value commitment
1. generate the range proof

The same steps needs to be repeated, when necessary, for blinding also a token amount.

Now it's important to note that here for generating the range proof it's required a blinding private key, that will be used as the `nonce` to pass to the `confidential.RangeProof` method.
When blinding an output, instead, we use a blinding pubkey and an ephemeral private key to produce a ecdh nonce hash. This just to make evident the difference between the generation of the 2 range proofs.

Said all these things, the blinder role should be updated by adding one more field:
```
issuanceBlindingPrivKeys [][2][]byte
```
this represents a list of couples of private blinding keys, one couple for each input containing an issuance.
A couple of private keys because one is used for blinding the asset amount, and one to do the same the token amount (when this is not defined this key will simply be nil, or an empty slice).

Finally, the signature of the new method should be something like:
```
func (*blinder) blindInputs() error 
```

**Comment by sekulicd** [comment]
I have few doubts:
1. In the attachment (issuance.txt) I issued an asset whose input is by default blinded.
```
"vin": [
    {
      "txid": "0cb92f7efac4f5e4666f5f1802a3fa2d128451271468171b051f8aaf403331a9",
      "vout": 2,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "is_pegin": false,
      "sequence": 4294967293,
      "txinwitness": [
        "304402202d72c364250fae6f5e0296d61452b2962413dada01dcc6344740c68961c95aec022064d1a97eb13dd172da32311c6cbb73a5230d2a9f772e79a896434bfbc05dff0e01",
        "0328d873d1986b28dc5d0d01ef068f6f8632cc0a992cb990e92388358de1652860"
      ],
      "issuance": {
        "assetBlindingNonce": "0000000000000000000000000000000000000000000000000000000000000000",
        "assetEntropy": "6611c807adcbd8534df2ba6ee5de0f50e137506e0ded4748060dd4582a1f7668",
        "isreissuance": false,
        "token": "54432ef840d5b1ac8490145d9c4aeb4e57f5927f1600de1786f0c8ab58041031",
        "asset": "90f98d2746fbfab0b3052923446112cbfcd2937819d76d7ced1c4a2850113c1a",
        "assetamountcommitment": "09662667ca3b4bae173c9769233760e3fd69c35e5a60bbd377c715c6e9731114ae",
        "tokenamountcommitment": "09a0ee40801887dafe4e2cd32e3189aee1c4aea5e6d60614d1bda2c0412dd2e2a0"
      }
    }
  ],
```
As you can see values, to be issued, are blinded but not asset and token itself.
I can confirm this with command - e1 listissuances:
```
 {
    "isreissuance": false,
    "token": "54432ef840d5b1ac8490145d9c4aeb4e57f5927f1600de1786f0c8ab58041031",
    "tokenamount": 1.00000000,
    "tokenblinds": "319453b322ce1e2efb8ca35b3fef1cb95abec551e39fe6b07826a348139715c7",
    "entropy": "6611c807adcbd8534df2ba6ee5de0f50e137506e0ded4748060dd4582a1f7668",
    "txid": "8a5df471bee180d426820b4a321ffd4e5c5cc64f0c5dbbd25f5c8df84d00a66d",
    "vin": 0,
    "asset": "90f98d2746fbfab0b3052923446112cbfcd2937819d76d7ced1c4a2850113c1a",
    "assetamount": 100.00000000,
    "assetblinds": "4a888586e056bc7ae1305c6ec523cd170733791c137ab59647f9d37b5953064d"
  },
```

2. Based on above is it correct that we only need to blind asset value and token value and not asset and token itself?

In order to generate asset/value blinding factor should I use function generateRandomNumber?

3. As you can see in the attachment (issuance.txt), issuance added in the input doesn't have any range proof(neither do outputs, only surjection proof).
I can see that TxInput struct has IssuanceRangeProof field:
```
type TxInput struct {
	Hash                []byte
	Index               uint32
	Sequence            uint32
	Script              []byte
	Witness             TxWitness
	IsPegin             bool
	PeginWitness        TxWitness
	Issuance            *TxIssuance
	IssuanceRangeProof  []byte
	InflationRangeProof []byte
}
```
To which field IssuanceRangeProof is mapped in the raw transaction (like one in the attachment), considering I don't see anything in inputs.
[issuance.txt](https://github.com/vulpemventures/go-elements/files/4788061/issuance.txt)

**Comment by altafan** [comment]
>Based on above is it correct that we only need to blind asset value and token value and not asset and token itself? And if this is true should we only use confidential.ValueCommitment to get Asset/Token value commitment?

This is correct... from the task description: *The fields that must be blinded in a input issuance are the asset and the token amount*)


>In order to generate asset/value blinding factor should I use function generateRandomNumber?

This is also correct.. again, from the description:
>For blinding an asset amount it's necessary to do the following steps:
> 1. generate a random value blinding factor
> 1. generate a random asset blinding factor
> 1. generate the asset commitment (needed only for the following step)
> 1. generate the value commitment
> 1. generate the range proof

3. The fact that you don't see a range proof when decoding the transaction doesn't mean that it doesn't exist at all. The elements CLI extracts basic information from the proof, ie. the min e max value range, that are more clear for the user rather than that very long string that a range proof is.
So, if an input/output is confidential, you can be sure that it contains a range proof.
