### ISSUE TITLE
Asset reissuance

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#107]
This must be taken into account for adding support for creating reissuance transaction:

https://github.com/ElementsProject/elements/issues/259

It will be mandatory to check that the input used for reissuing the asset (actually must be a token prev output) is confidential.

**Comment by altafan** [comment]
Given the Elements issue above, and stated that similar to `AddIssuance`, this should be a function of the `updater` type, it will be necessary that the chosen partial input has a `(Non)WitnessUtxo` so that we can check that it's actually a confidential input, otherwise we should return an error.

This error should suggest the user move his reissuance token to a confidential address otherwise he will never be able to reissue his asset.

**Comment by altafan** [comment]
It is mandatory that the input that contains the reissuance of the asset is the token output generated when this was issued.

Given this constrain, maybe it would be better that we provide a function that adds an input (the prevout token) and a reissuance, rather than expecting that the input is already present in the partial transaction and just add a reissuance to it?

cc @tiero

**Comment by tiero** [comment]
ACK

**Comment by tiero** [comment]
Could you split among the tickets you are working on already? @altafan
