### ISSUE TITLE
FromScript should set both Script and WitnessScript

### ISSUE THREAD

**Issue by tiero** [vulpemventures/go-elements#122]
At the moment the Script field is nil. This factory method should follow the same behavior of FromPublicKey and set both fields, so the user could generate both types of addresses (legacy or segwit)

**Comment by sekulicd** [comment]
@tiero can you advise which test case is failing to create expected address?

**Comment by tiero** [comment]
> @tiero can you advise which test case is failing to create expected address?

We do not have a proper test. At the moment we use fromScript to just get the corresponding hash or withnessHash. 

Given whatever script (eg of a P2WPKH) and get out the legacy script, useful for signing.

**Comment by sekulicd** [comment]
> Given whatever script (eg of a P2WPKH) and get out the legacy script, useful for signing.

Aren't we doing that already [here](https://github.com/vulpemventures/go-elements/blob/e477e50f71e93abdaa0aaca54c41922e52e5d907/payment/payment.go#L164)? In case of P2PKH we set both information we are able to, public key hash and script.

**Comment by tiero** [comment]
Yes, we do for p2pkh, but [we should do it also for witness one.](https://github.com/vulpemventures/go-elements/blob/e477e50f71e93abdaa0aaca54c41922e52e5d907/payment/payment.go#L157)
 
when we sign a tx that spends a p2wpkh we still need the legacy script to produce the correct signature hash.

**Comment by tiero** [comment]
example on how to do it having the legacy hash 
`legacyScript := append(append([]byte{0x76, 0xa9, 0x14}, Hash...), []byte{0x88, 0xac}...)`
