### ISSUE TITLE
reversed reissuance token flags ?

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/go-elements#128]
It's possible that I missed something but looking at the Elements code and the go-elements code for the token generation we can notice that:

In _issuance.cpp_ the confidential flags are 0x000....001 (for not confidential issuance)  or 0x0000...002 (for confidential one).  (https://github.com/ElementsProject/elements/blob/master/src/issuance.cpp#L49)
Whereas in _issuance.go_, flags are 0x1000...000 and 0x2000...00. (https://github.com/vulpemventures/go-elements/blob/master/transaction/issuance.go#L166)

Edit: libwally generates token in the same way -> https://github.com/ElementsProject/libwally-core/blob/master/src/transaction.c#L2929

It seems that these two implementations are different.

**Comment by altafan** [comment]
Hi @louisinger,

That's interesting, we actually used [libwally](https://github.com/ElementsProject/libwally-core/blob/master/src/transaction.c#L2917) as the reference implementation for this.

We haven't noticed this before, but it seems to me that there are differences in Elements' repos.
Maybe the `uint256S` function actually reverses the string when parsed in "bytes". It would be nice to check this

**Comment by louisinger** [comment]
Indeed, Uint256S inverts the bytes during parsing here: https://github.com/ElementsProject/elements/blob/master/src/uint256.cpp#L41
I didn't think to look this way. Any idea why? A big/little endian story?

**Comment by altafan** [comment]
Not sure why, but I know this is inherited from Bitcoin, wanna try to ask to Satoshi? :)

Closing this.
