### ISSUE TITLE
Wrong hash returned for issuance tx

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#169]
[Here]() you can find an example of a transaction containing an issuance that I was able to broadcast on regtest with hash `4f2560d018b2600399ad960284f5d13f02a978de8673c8950bf8f9cd265ec1a6`.

The method `Transaction.TxHash()` returns `16a2d64e1e9d0fb233169a4d08a222a0562895bd3cbbe1783c66aeadd5320f26` instead.

The bug hasn't been identified yet, but it could reside somewhere [here](https://github.com/vulpemventures/go-elements/blob/e8047656b1060fadefba83048c97edc502a4e532/transaction/transaction.go#L723) where the input issuance is serialized.

**Comment by tiero** [comment]
Has this been closed? @sekulicd

**Comment by sekulicd** [comment]
> Has this been closed? @sekulicd

https://github.com/vulpemventures/go-elements/pull/171
