### ISSUE TITLE
[PSET Input] Create

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#18]
A method `NewPsetInput` accepting either a witness or non witness utxo and returning a `*PInput` must be added to the package in order to be able to create inputs.

Ref #17.

**Comment by tiero** [comment]
Should be possible to specify a sighHashType too. Could you add this in the spec? @altafan

**Comment by altafan** [comment]
Inspired by `btcutil` [implementation](https://github.com/btcsuite/btcutil/blob/master/psbt/partial_input.go#L15), this would be our pset input type definition:

```
type PInput struct {
	NonWitnessUtxo     *transaction.Transaction
	WitnessUtxo        *transaction.TxOutput
	PartialSigs        []*PartialSig
	SighashType        txscript.SigHashType
	RedeemScript       []byte
	WitnessScript      []byte
	Bip32Derivation    []*Bip32Derivation
	FinalScriptSig     []byte
	FinalScriptWitness []byte
	Unknowns           []*Unknown
}
```
