### ISSUE TITLE
the hex-encoded public key of the issuer is missing IssuanceContract struct

### ISSUE THREAD

**Issue by tiero** [vulpemventures/go-elements#182]
[Here](https://github.com/vulpemventures/go-elements/blob/71dd075222b5880722fcdb922fee3150cd5f383e/transaction/issuance.go#L20) we should include the Issuer Pub Key as weel 

reference specification

https://docs.blockstream.com/liquid/developer-guide/proof-of-issuance.html#contract-json-fields

**Comment by tiero** [comment]
Test need to be updated and keys must be sorted lexographically to produce right contract hash

https://docs.blockstream.com/liquid/developer-guide/proof-of-issuance.html#contract-hash

**Comment by sekulicd** [comment]
As per doc, json sorts key lexographically by default, as for the tests need to check with pietro on how fixtures were generated since there were no pubkey

**Comment by sekulicd** [comment]
> As per doc, json sorts key lexographically by default, as for the tests need to check with pietro on how fixtures were generated since there were no pubkey

Actually this is not true as only maps are sorted and not structs.
@tiero

**Comment by tiero** [comment]
> json sorts key lexographically 

good to know, thanks

> how fixtures were generated

I guess they have been generated manually.

You can use GET `/contract/validate` to add test for the contract hash 

ie.


```json
{"version":0,"issuer_pubkey":"02a9a7399de89ec2e7de876bbe0b512f78f13d5d0a3315047e5b14109c8bac38f2","name":"Tiero Token","ticker":"TIERO","entity":{"domain":"tiero.github.io"},"precision":0}
```

Expected hash

`cc64512512e0bc75ff028115bb6c466393dc91f257e3f883a58154b34dbca836`
