### ISSUE TITLE
[PSET Input] (De)Serialize

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#19]
A `serialize` method accepting a `io.Writer` where to write the serialized inpu must be added to the package. 
The same applies for the `deserialize` method that deserialize the raw inputs from the given `io.Reader`.

Ref #17.

**Comment by tiero** [comment]
Can you elaborate more? the serialization you are talking about in this issue it's relative to base64 encoding?

**Comment by altafan** [comment]
This is the serialization of an input of the PSET.
The serialization of the whole PSET includes this building block.

The implementation linked in the referenced issue is totally reusable and needs very few changes to fit our necessities.
