### ISSUE TITLE
How to Implement psbtStart.addOutput for a PSBT in go-elements

### ISSUE THREAD

**Issue by infra403** [vulpemventures/go-elements#222]
`
                const atomPayload = new AtomicalsPayload(copiedData);
                const updatedBaseCommit: { scriptP2TR, hashLockP2TR, hashscript } = prepareCommitRevealConfig(this.options.opType, fundingKeypair, atomPayload)
                // console.log("updatedBaseCommit", JSON.stringify(updatedBaseCommit))
                // console.log("fundingKeypair", JSON.stringify(fundingKeypair))

                let psbtStart = new Psbt({ network: NETWORK });
                psbtStart.setVersion(1);
                psbtStart.addInput({
                    hash: fundingUtxo.txid,
                    index: fundingUtxo.index,
                    witnessUtxo: { value: fundingUtxo.value, script: Buffer.from(fundingKeypair.output, 'hex') },
                    tapInternalKey: fundingKeypair.childNodeXOnlyPubkey,
                });
                // console.log("fundingUtxo", JSON.stringify(fundingUtxo))
                // console.log("witnessUtxo script",  Buffer.from(fundingKeypair.output, 'hex'))
                // console.log("tapInternalKey", fundingKeypair.childNodeXOnlyPubkey)

                psbtStart.addOutput({
                    address: updatedBaseCommit.scriptP2TR.address,
                    value: fees.revealFeePlusOutputs
                });

                this.addCommitChangeOutputIfRequired(fundingUtxo.value, fees, psbtStart, fundingKeypair.address);

                psbtStart.signInput(0, fundingKeypair.tweakedChildNode);
                // console.log("tweakedChildNode", fundingKeypair.tweakedChildNode)

                psbtStart.finalizeAllInputs()
                let prelimTx = psbtStart.extractTransaction();`

**Comment by tiero** [comment]
You should use psetv2 package. Refer to these tests https://github.com/vulpemventures/go-elements/blob/master/psetv2/pset_test.go
