### ISSUE TITLE
Let a user spend an unconfidential input and broadcast the transaction

### ISSUE THREAD

**Issue by tiero** [vulpemventures/go-elements#39]

**Comment by altafan** [comment]
This should be done by an e2e test into the `pset` package.

To accomplish this, we would need a bitcoin regtest node for broadcasting a transaction after extracting the transaction from the `Pset` wrapper. 

I think the way to go could be creating a bash script with the following steps

1. download nigiri travis and start it up
2. run tests
3. delete nigiri travis folder

For development, it would be annoying to always have to download and delete nigiri-travis. It would be preferable to have a local nigiri running and just run the tests.

Given this, the bash script should expect an argument that lets to skip steps 1 and 3.

We should also add an environment variable `API_URL` to let the user define the API url of nigiri-chopsticks.
