### ISSUE TITLE
[Payment] FromPublicKeys factory

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#43]
The `payment` package is almost complete. I would say that it still misses a factory function for creating a payment given multiple public keys in order to create a payment for a multisig script.

Given that, we should add a `FromPublicKeys` method that accepts a list of public keys `pubkeys []*btcec.PublicKey`, a threshold `m int`  and of course a network `net *network.Network`. The first 2 arguments should be used to create the multisig script:
```
OP_<M> pubkeys OP_<N> OP_CHECKMULTISIG
```

and then use the `FromScript` factory to return a new `*Payment`.

**Comment by tiero** [comment]
An example could be found in the btcd repo [MultiSigScript](https://github.com/btcsuite/btcd/blob/86fed781132ac890ee03e906e4ecd5d6fa180c64/txscript/standard.go#L483)

**Comment by sekulicd** [comment]
> An example could be found in the btcd repo [MultiSigScript](https://github.com/btcsuite/btcd/blob/86fed781132ac890ee03e906e4ecd5d6fa180c64/txscript/standard.go#L483)

Shall we use this method in this library to generate script bytes or I should create it based on the same logic?

**Comment by altafan** [comment]
I think it's a good idea to reuse it, instead of reimplementing 👍

**Comment by tiero** [comment]
I think reusing the [scriptbuilder](https://github.com/btcsuite/btcd/blob/86fed781132ac890ee03e906e4ecd5d6fa180c64/txscript/scriptbuilder.go#L37) would be nice to inherith all the checks already
