### ISSUE TITLE
Add GoDoc Usage instructions in the homepage

### ISSUE THREAD

**Issue by tiero** [vulpemventures/go-elements#52]
Describe how a Go developer should import the library (eg. go get) and some highlight on how to generate and address etc.. in the main Readme

**Comment by altafan** [comment]
Is it enough to add a link in the readme pointing to the [example](../blob/master/example.go)?

**Comment by tiero** [comment]
still would be missing installing instructions. I think some main functions in the Readme in markdown could be nice.

Thax example.go file would be used by the godoc pkg documentation we'll build
