### ISSUE TITLE
[secp256k1-zkp] Bindings for ecdh module methods

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#54]
We need to add the bindings for the native C functions of the `ecdh` module listed below:
* [`secp256k1_ecdh`](https://github.com/ElementsProject/secp256k1-zkp/blob/secp256k1-zkp/src/modules/ecdh/main_impl.h#L29)

We could reuse the one implemented in this [repo](https://github.com/olegabu/go-secp256k1-zkp/blob/master/secp256k1.go#L485).

For testing, we should use the vectors from the [js version](https://github.com/vulpemventures/secp256k1-zkp/blob/master/test/fixtures/ecdh.json).

**Comment by sekulicd** [comment]
@altafan I think we can't reuse code from [this](https://github.com/olegabu/go-secp256k1-zkp/blob/master/secp256k1.go#L485) repo as it looks to me that it is referencing different C code.

I think the example that you recommended to look up to is using C lib from [this](https://github.com/mimblewimble/secp256k1-zkp) repo and in our project, we are referencing [Elements C lib](https://github.com/ElementsProject/secp256k1-zkp).

PSB difference in a method signature:
1. Method [secp256k1_ecdh](https://github.com/ElementsProject/secp256k1-zkp/blob/dc4181ae3074b317cb0ec48168829adf4acfb675/include/secp256k1_ecdh.h#L42) of the Elements C lib is receiving 6 params 
2. Method [secp256k1_ecdh](https://github.com/mimblewimble/secp256k1-zkp/blob/5b39fbf7f1e16e126404791923511723c4c0876d/include/secp256k1_ecdh.h#L20) of the example you recommended to be used, is receiving 4 params

I checked if anybody else in [Github](https://github.com/search?q=C.secp256k1_ecdh+extension%3A.go&type=Code&ref=advsearch&l=&l=) referenced method secp256k1_ecdh with 6 params but search returned only calls with 4 params.

What do you think, am I missing something?

**Comment by altafan** [comment]
You're absolutely right, but we can still reuse that implementation since we actually won't set the last to args of the `secp256k1_ecdh` function. You can see that in the [js version](https://github.com/vulpemventures/secp256k1-zkp/blob/master/src/main.c#L21) we force them to be `NULL`.
