### ISSUE TITLE
[secp256k1-zkp] Bindings for rangeproof module

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#55]
We need to add the bindings for the native C functions of the `rangeproof` module listed below:
* [`secp256k1_rangeproof_sign`](https://github.com/ElementsProject/secp256k1-zkp/blob/secp256k1-zkp/src/modules/rangeproof/main_impl.h#L278)
* [`secp256k1_rangeproof_info`](https://github.com/ElementsProject/secp256k1-zkp/blob/secp256k1-zkp/src/modules/rangeproof/main_impl.h#L222)
* [`secp256k1_rangeproof_verify`](https://github.com/ElementsProject/secp256k1-zkp/blob/secp256k1-zkp/src/modules/rangeproof/main_impl.h#L260)
* [`secp256k1_rangeproof_rewind`](https://github.com/ElementsProject/secp256k1-zkp/blob/secp256k1-zkp/src/modules/rangeproof/main_impl.h#L237)

For testing, we should be able to reuse the vectors of the [js version](https://github.com/vulpemventures/secp256k1-zkp/blob/master/test/fixtures/rangeproof.json).

NOTE: in these test vectors, values are passed as strings since js has limitations on the representation of big numbers. Here we could use directly values as numbers so all the occurrences should be changed from string to numbers.

**Comment by tiero** [comment]
Should this be closed?

**Comment by altafan** [comment]
Closed by [#2](https://github.com/vulpemventures/go-secp256k1-zkp/pull/2).
