### ISSUE TITLE
Confidential package

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#59]
To support the blinding/unblinding of elements utxos we need to create the functions that actually use the methods of the secp256k1-zkp lib.
We can take inspiration by the js module we created in the [`liquidjs-lib`](https://github.com/vulpemventures/liquidjs-lib/blob/master/ts_src/confidential.ts) library.

We should then create a `condifential` package that collects the methods for the following purposes:

* Creating a nonce hash from a keypair
* Unblinding a utxo given a blinding private key.
* Creating a final value blinding factor for the last transaction output.
* Creating an asset commitment.
* Creating a value commitment.
* Creating a range proof.
* Creating a surjection proof.

All the points in this bullet list will be expanded in dedicated issues, but all of them represent a necessary step in order to implement the pset's Blinder role of #45.

**Comment by tiero** [comment]
I guess could be closed? @altafan
