### ISSUE TITLE
[Transaction] Method for generating issuance asset entropy

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#80]
In order to support the non-confidential issuance of new assets, we need to define some methods for the `*TxIssuance` type in the transaction package for generating the asset entropy and calculating the asset hash and reissuance token from it.

A **non-confidential** issuance transaction is a transaction that contains:
* one input that includes a `TxIssuance`, that describes the entropy of the asset, its issuance amount and the reissuance token amount
* one output for the issuance amount
* one output for the reissuance token amount (if > 0)
Both the outputs are, of course, locked with the script of the minter of the asset.

We need to define a `GenerateAssetEntropy` function for `*TxIssuance` type that generates the entropy of an asset from a tx hash, an input index (this is the index of the issuance transaciton, not the prevout index!) and the hash of a Ricardian contract that represents the asset itself.
[Here](https://github.com/vulpemventures/go-elements/issues/26#issuecomment-638228277) you can see an example of a contract.

It would be better if the sha256 hash of the contract was done by our `GenerateAssetEntropy` so we define a type structure for the contract like the following and the user is aware of how to properly create a contract:

```
type Entity struct {
   Domain string
}

type Contract struct {
   Name string
   Ticker string
   Version uint
   Precision uint
   Entity Entity
}
```

The function should just return an error if any occur, otherwise it has the side effect of changing the `AssetEntropy` field of the issuance with the one generated.
This should be the function signature:

```
func (*TxIssuance) GenerateAssetEntropy(inTxHash []byte, inTxIndex, contract Contract) error {}
```

[Here](https://github.com/ElementsProject/libwally-core/blob/master/src/transaction.c#L2748) you can find the reference implementation for this function, below a quick explanation of the code:
* step 1: sha256 double hash of the serialized `[txHash, uint32LE(inputIndex)]`
* step 2: **midstate** sha256 hash of serialized `[stepOneResult, sha256(contract)]`

**Comment by tiero** [comment]
https://github.com/btcsuite/fastsha256/blob/637e656429416087660c84436a2a035d69d54e2e/sha256.go#L200
