### ISSUE TITLE
[Transaction] Method for calculating reissuance token  

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#82]
We need to define a `GenerateReissuanceToken` method for the `*TxIssuance` type that expects a flag argument that can assume only the values `0` or `1` and calculates from it and from the entropy of the issuance type the hash of the reissuance token as the sha256 hash of the serialized entropy and the `0x??..00` 32-byte array. `??` is actually the given flag + 1.
[Here](https://github.com/ElementsProject/libwally-core/blob/master/src/transaction.c#L2816) you can see the reference libwally's implementation.

**Comment by tiero** [comment]
The values `0` and `1` refers to blinding? @altafan

the number of tokens is not defined at this step?

**Comment by altafan** [comment]
Yes, the `0` flag is used for non confidential, while `1` for confidential.
This produces the hash of the reissuance token.. you can see it as a special asset that is used to re-issue the one it refers to in some way.
The token amount is specified by the user, but generally the amounts are not used to create the hash of the asset and the token.
