### ISSUE TITLE
[Payment] FromPayment

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#9]
A `FromPayment` function similar to the existing `FromPublicKey` one must be added to the `payment` package in order to return a `Payment` from another `*Payment` struct and a network.

Ref: #8.

**Comment by tiero** [comment]
Can you elaborate better on what you expect to be a Redeem script? What's the difference then from #10 ?

**Comment by altafan** [comment]
The `Redeem` type is used for nested script hash addresses, for example for a p2sh-p2wpkh or p2sh-p2wsh.

The `FromRedeem` function would set the `Hash` field by computing the `hash160` of `Redeem.Hash`.

In the light of these considerations, I'm re-evaluating the usefulness of `Script` and now thinking that it would just become a copy of the `Hash` field and it would be better to drop it.

**Comment by altafan** [comment]
`Script`, instead, is needed for non-nested p2sh addresses, like multisigs:
from this field, that in our example would contain the script formed by the _n_ public keys and the _m_ threshold, we would derive the `Hash`, as always, by computing the `hash160`.

`FromScript` let the user to create his own script and pass it to `Payment` to get the p2sh or p2wsh address.

We would likely implement also a `FromPubkeys` or whatever method to facilitate the creation of a multisig address.

**Comment by tiero** [comment]
@altafan Please make some example in pseudo code of what is needed, some examples of inputs and expected outputs.

**Comment by altafan** [comment]
p2sh-p2wpkh example:

```
// create a p2wpkh first
p2wpkh := FromPublicKey(myPubkey)
// now nest the payment into a p2sh
p2sh := FromRedeem(p2wpkh)
// finally get the address
address := sh.ScriptHash()
```

In the first step, we simply generate a Payment from a public key.
Now, instead, of deriving the base58/bech32 address from the payment's `Hash`, we want to wrap it into another payment.
So, in the second step, we make use of `FromRedeem` to nest the p2wpkh into a p2sh.
This technically means taking the hash of the given payment and hashing it again to produce the final hash that will be encoded, in this case, in base58 format.

@sekulicd please, ask if it's still unclear.

**Comment by tiero** [comment]
@sekulicd @altafan  I edited the description of the task because actually it's NOT a **redeem script** what we need to pass as a parameter, but another Payment object. For that, we have the `FromScript` where (I suppose) we would need to pass the reddems script as array of bytes or hex string.

**Comment by altafan** [comment]
Good point. I think it's better renaming.

**Comment by tiero** [comment]
@sekulicd we updated the name of the function, this should lead to less confusion I think.

**Comment by sekulicd** [comment]
@altafan can you, please, also edit redeem to payment in your comments where it is needed so we avoid confusion?
