### ISSUE TITLE
Add golint to CI pipeline

### ISSUE THREAD

**Issue by tiero** [vulpemventures/go-elements#93]
Would be nice to add automatic linting to have an uniform style using `golint` package. The CI pipeline should enforce it in the same way we do for `gofmt`

**Comment by altafan** [comment]
From the documentation of the tool:
>The suggestions made by golint are exactly that: suggestions. Golint is not perfect, and has both false positives and false negatives. Do not treat its output as a gold standard. We will not be adding pragmas or other knobs to suppress specific warnings, so do not expect or require code to be completely "lint-free". In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process.

Ok, we would actually use it for testing rather than for building the lib, but do you think it's still the case of adding it even if it's not recommended?
