### ISSUE TITLE
[Confidential] Mandatory change to RangeProof

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#96]
While studying how to blind an issuance transaction, I discovered that, when producing the range proof for blinding the asset/token amount of an input issuance, only one (private) key is used, rather than as done for the outputs where an ephemeral private key and a public key are used.
[This](https://github.com/ElementsProject/elements/blob/master/src/blind.cpp#L464) is taken from the elementsd implementation, while [this](https://github.com/ElementsProject/elements/blob/master/src/blind.cpp#L540) shows how the nonce is generated right after, when generating the proofs for the outputs.

We taylored our `RangeProof` function of the *confidential* package to always expect a private and a public key, for then generating the ecdh hash passed as a [*nonce*](https://github.com/vulpemventures/go-elements/blob/master/confidential/confidential.go#L178) to the CGO binding function.

We basically discovered that this so called *nonce* can be an ecdh hash of a key pair, or just a private key, and we support only the first option at the moment.

We could change directly the implementation of our `RangeProof` function by checking if the provided public key is nil, and in that case setting the nonce to the provided private key, otherwise, it would work as it does right now.

@tiero @sekulicd do you have other ideas?

**Comment by tiero** [comment]
> We could change directly the implementation of our `RangeProof` function by checking if the provided public key is nil, and in that case setting the nonce to the provided private key, otherwise, it would work as it does right now.

I would make this more explicit, hence either having two wrappers on top of `RangeProof` one for an asset issuance input and one for output or passing a flag (and do the relative checks) to the function to indicate the behavior.

**Comment by altafan** [comment]
So far, we decided to not create the nonce inside the `RangeProof` method, but rather expecting it as argument of the function, thus in the `RangeProofInput` we replace the `BlindingPubkey` and `EphemeralPrivkey` with a `Nonce` field.
Hence, it will be the caller of this function that will have the responsability to pass the correct nonce.
