### ISSUE TITLE
[PSET] Blinding transaction issuance inputs

### ISSUE THREAD

**Issue by altafan** [vulpemventures/go-elements#97]
The blinder role at the moment is represented by a `BlindOutputs` function that, as the name suggests, takes care of blinding **only the outputs** of a transaction.

When blinding a transaction that contains one or more issuances, instead, the blinder should blind **also the inputs** of the transaction that contain an issuance.

The issuance block contained by a tx input defines the asset total amount issued and the number reissuances that can be done, along with other information. These 2 amounts need to be substituted by commitments when blinding the transaction and also the respective range proofs must be added. 

So, blinding an input issuance means producing a commitment and a range proof for the asset amount and also for the token amount (if > 0) just as done for the outputs except for the fact that here it is not needed to calculate a final vbf.
So, at least for the asset amount, the blinder should do the following steps:
1. generate a random value blinding factor
2. generate a random asset blinding factor
3. generate the asset commitment (needed only for the following step)
4. generate the value commitment
5. generate the range proof

The last step deserves a focus:
as explained in #96, we don't need to calculate an ecdh hash from a key pair when generating the range proof here, but rather only a private key.
This means that, along with the changes that will be made to fix the linked issue, the `blinder` type needs to be extended with a new field `issuanceBlindingPrivKeys [][2][]byte`.
This weird type is due to the fact that the proofs for asset amount commitment and the token amount commitment (if > 0) should be generated by using 2 different keys. The public keys from them should be used to blind the issuance outputs of the transaction.

**Comment by tiero** [comment]
Could this issue be split up in more smaller tickets? @altafan
